source 'http://rubygems.org'

    gem 'rails', '3.0.3'
    gem 'mysql2'
    gem 'inherited_resources'
    gem 'RedCloth'
    gem 'friendly_id', '~> 3.2.1'
    gem 'kaminari'
    gem 'faker', '0.3.1'
    gem 'populator'
